### PR TITLE
feat: support `doctrine/orm` 3

### PR DESCRIPTION
**Pull request by kbond**
TODO:

- [ ] sqlite changes. We don't currently test but there are some breaking changes when using `ResetDatabase` with sqlite

### CODE REVIEW

**Comment by nikophil** [comment]
won't it be a PITA to maintain tests for both versions?

**Comment by kbond** [comment]
Possibly, but if we bump the min orm to latest 2.x, perhaps it won't be a problem?

**Comment by kbond** [comment]
I think some of the work done in https://github.com/symfony/maker-bundle/pull/1439 could help us here.

**Comment by jrushlow** [comment]
`MakeTestRunner::configureDatabase()` has the logic we needed to get sqlite to work with the new `orm` - https://github.com/symfony/maker-bundle/blob/d9574302ee67c23ae5c803556f2b779c3b0b94a2/src/Test/MakerTestRunner.php#L156

**Comment by nikophil** [comment]
closed in favor of https://github.com/zenstruck/foundry/pull/569

**Pull request closed without merging**
