### PR TITLE
Improve return types of Factory

### PR DESCRIPTION
**Pull request by andersonamuller**
At least PHPStorm was not able to autocomplete without these changes.

### CODE REVIEW

**Comment by nikophil** [comment]
Hi @andersonamuller 

thanks for this PR.

could you show me which kind of autocompletion problem this PR fixes?

those return types create errors in static analysis, but I'm wondering if it is not a false positive...

**Comment by nikophil** [comment]
https://phpstan.org/r/36d05c9d-1309-4a9a-87b2-91235c23a796  :shrug:

**Comment by andersonamuller** [comment]
Sorry @nikophil. I haven't digged deep enough. The issue is with the PHPStorm static analyzer.

When I try something like:
```php
$object = MyFactory::new()->with([...])->create();
```

The autocomplete for the `$object` only shows methods of the `\Doctrine\Persistence\ObjectRepository\Proxy` class.

When I use 
```php
$object = MyFactory::createOne([...]);
```
Then is all fine. Or with the patch I submitted then PHPStorm is able to resolve the type.

**Comment by nikophil** [comment]
Would you mind to test this PR?
https://github.com/zenstruck/foundry/pull/675

Everything is fine for me with this fix

**Comment by andersonamuller** [comment]
I tested that PR and unfortunately it doesn't help with my case. I had to add the method annotation to my factory class.

```php
/**
 * @extends PersistentObjectFactory<MyObject>
 * 
 * @method MyObject create()
 */
final class MyFactory extends PersistentObjectFactory {}
```

**Comment by nikophil** [comment]
ok thanks, I'll try using `with()` and check what's going on. I'd really like end factory to not need these `@method` annotations

**Comment by nikophil** [comment]
hey @andersonamuller 

may I ask what's your PHPStorm version? in all my tests have the same result:
```php
// 
MyFactory::new()->create();
```

**Pull request closed without merging**
