### PR TITLE
[refactor] modernize code with rector

### PR DESCRIPTION
**Pull request by nikophil**
based on #326 

I played around with Rector today.

Mainly modernized the code to php8:
- added arrow function
- typed everything that should be (except for some edge case with BC problems)
- used property constructor promotion when possible

### CODE REVIEW

**Review by kbond — COMMENTED** [review]
Nice! Should we switch to attributes for the test entities?

**Comment by nikophil** [comment]
I made the mistake and... had to rollback since sf4.4 + lowest doctrine does not support it :disappointed:

**Comment by kbond** [comment]
Would bumping the min doctrine req help?

What do you think about requiring 5.4+?

**Comment by nikophil** [comment]
> What do you think about requiring 5.4+?

not a huge fan, since it's still maintained

**Comment by kbond** [comment]
Ok, forgot it had another year

**Pull request merged**
