### PR TITLE
fix: allow non object state in stories

### LINKED ISSUE #697: Regression on story states for non object state
Since 2.0.5, story states seems to be broken for any values added with `addState` that are not objects.

`addState` allows `mixed` type, however in the `getState` method, we now call a `refresh` on `PersistenceManager` that expect an object. Hence the error in my case : 

```
TypeError: Zenstruck\Foundry\Persistence\PersistenceManager::refresh(): Argument #1 ($object) must be of type object, array given, called in /srv/api/vendor/zenstruck/foundry/src/Story.php on line 140
```

https://github.com/zenstruck/foundry/blob/6105a364f14dd2a29e3a76eb5127ce2f24b1958d/src/Story.php#L135

### PR DESCRIPTION
**Pull request by Brewal**
fixes #697

### CODE REVIEW

**Comment by nikophil** [comment]
Hi @Brewal 

thanks for this fix!

could you please add a test which ensures there won't be a regression anymore?

**Comment by Brewal** [comment]
@nikophil sure, I'll do that soon.

**Comment by Brewal** [comment]
@nikophil I added some assertions in StoryTest. Hope that's good enough. The tests do break without the fix.

**Review by nikophil — APPROVED** [review]

**Comment by nikophil** [comment]
super nice, thank you for this fix!

**Comment by nikophil** [comment]
your fix is released in [2.1.0](https://github.com/zenstruck/foundry/releases/tag/v2.1.0)

**Pull request merged**
