### PR TITLE
chore: migrate phpunit config-file for phpunit 9 format

### PR DESCRIPTION
**Pull request by Chris53897**
With the changed `xsi:noNamespaceSchemaLocation`, the ide can understand it corret locally.

### CODE REVIEW

**Comment by OskarStark** [comment]
You should keep the indentation

**Comment by Chris53897** [comment]
@OskarStark Is it better now, or did i miss an indentation ?

**Review by nikophil — APPROVED** [review]
thanks @Chris53897 !

**Comment by kbond** [comment]
We need to update `phpunit-dama-doctrine.xml.dist` too.

**Pull request merged**
