### PR TITLE
minor: remove `faker()`/`defaultObjectInstantiator()` from `FactoryManager`

### PR DESCRIPTION
**Pull request by kbond**

### CODE REVIEW

**Comment by kbond** [comment]
I'll fix this up tomorrow.

**Comment by kbond** [comment]
@nikophil, any idea why the phpstan is failing on that line now?

**Comment by nikophil** [comment]
this is so strange oO
"go home, PHPStan, you'r drunk"

**Comment by nikophil** [comment]
hum I don't know :thinking: 
I'll have a closer look later if you don't find

**Comment by kbond** [comment]
Ignoring for now - it's clearly invalid. I think, previously, the `iterable $factories` property wasn't type-hinted so phpstan didn't complain.

**Pull request merged**
