### PR TITLE
minor: add missing generic return phpdoc

### PR DESCRIPTION
**Pull request by ekvedaras**
This was driving me nuts.

Please let me know if I missed some reason why this should not be here :)

### CODE REVIEW

**Comment by nikophil** [comment]
Hi @ekvedaras 

thanks for this.

just to know, is it improving your IDE's autocompletion?

because static analysis tools are inferring the return type from the parent method `Factory::create()` where the return type is actually present.

**Comment by ekvedaras** [comment]
Yes, this is for IDE. `Factory::createOne()` is understood fine, but `Factory::new()->create()` looses the type without this.

**Comment by ekvedaras** [comment]
Although now I'm testing this on actual project instead of this repo only and it is still getting confused and thinks it returns a proxy 🤔 Not wrong, but doesn't understand the entity

**Comment by ekvedaras** [comment]
Hmm, can't make it to work on an actual project. Don't really see what's wrong now. I know it is possible as I've built similar factory thing myself, however it was simpler. So either phpstorm is getting lost somewhere in the code or symfony plugin is interfering (don't know if it does anything with foundry).

I will play around a bit more later. If I can't make it work, will close.

**Comment by nikophil** [comment]
yeah, autocomplete for proxies is broken :/

https://github.com/zenstruck/foundry/issues/656

The whole "type system" is fine, PHPStan is tested and OK, but somehow PHPStorm does not undderstand something. My first guess was to add a bunch of `@method` to `PersistentProxyObjectFactory`, but I failed to make it work... I have to dig a little bit more in this way...

**Comment by ekvedaras** [comment]
Probably has something to do with depth. If I for example extend `Factory<User1>` `create()` will work. Anything else like `ObjectFactory<User1>` won't anymore unless it is a static call like `createOne()`. Might simply be a bug/limitation of phpstorm.

**Comment by nikophil** [comment]
see https://github.com/zenstruck/foundry/pull/675 where the solution is wider

**Pull request closed without merging**
