### PR TITLE
Add attributes to ModelFactory/RepositoryProxy random methods

### PR DESCRIPTION
**Pull request by kbond**
@Kalyse wdyt?

### CODE REVIEW

**Comment by Kalyse** [comment]
O nice. You moved fast. I've just got the kids due back in about ten minutes, so I don't have the opportunity to checkout this code, but the review looks like it's exactly what I needed. That's really perfect and saves me a lot of boilerplate on all my Stories. 

I'll run through the actual implementation tomorrow against my own tests.

**Comment by kbond** [comment]
Ok, I'll wait to hear back from you - no rush!

**Comment by Kalyse** [comment]
Works like a charm for my use-case. 
What is your usual PR-merge process? I'm not in any rush either for being able to use the master branch, just would be good to set a reminder to update my composer.json

**Review by wouterj — APPROVED** [review]

**Comment by kbond** [comment]
@Kalyse great to hear! I don't have a process formalized. I just released [v1.7.0](https://github.com/zenstruck/foundry/releases/tag/v1.7.0).

**Pull request merged**
