### PR TITLE
chore(CI): Enable documentation linter

### LINKED ISSUE #446: ci: Lint documentation
https://github.com/OskarStark/doctor-rst

### PR DESCRIPTION
**Pull request by cezarpopa**
Hi,

I've updated the ci.yml to include a documentation linter step, along with a basic initial configuration for the linter.

Additionally, I've modified the main README to include instructions on how to use the linter locally. If there are any additional rules you'd like to be included in the YAML configuration for the linter, please let me know. I'd be happy to make those changes.

Thank you!

fixes #446

### CODE REVIEW

**Comment by nikophil** [comment]
Hi @cezarpopa 

thanks for this!

what if we use Symfony doc's config as is?
https://github.com/symfony/symfony-docs/blob/7.1/.doctor-rst.yaml

any thoughts @kbond @OskarStark?

**Comment by kbond** [comment]
As the docs are hosted on symfony.com I think it makes sense to use their config. But @cezarpopa, is there a reason not to?

**Comment by cezarpopa** [comment]
Hi @nikophil, @kbond ,

That sounds great, I'll carry over the Symfony config, make any required tweaks for the Symfony-specific areas I've noticed, test it, and amend the current PR.

Sorry about the back and forth with this 😅

Thank you!

**Comment by kbond** [comment]
No problem, thanks for your efforts!

**Review by kbond — APPROVED** [review]

**Comment by cezarpopa** [comment]
Hi everyone 👋 

I believe that should be it.

I've added a detailed description around the rationale of this [commit](https://github.com/zenstruck/foundry/pull/657/commits/5f92aca8cd842e96bd8c8294982a785153a08b22). In summary, I have adjusted the .doctor-rst.yaml configuration file by removing Symfony-specific directives and configurations that were not relevant to the project.

### Changes Made:
1. **Removed Symfony-Specific Version Directives:**
   - The following directives were removed as they pertain to Symfony's versioning scheme and are not applicable to Foundry:
     ```
     versionadded_directive_major_version:
         major_version: 7

     versionadded_directive_min_version:
         min_version: '7.0'

     deprecated_directive_major_version:
         major_version: 7

     deprecated_directive_min_version:
         min_version: '7.0'
     ```

2. **Excluded Irrelevant Rules:**
   - The rules excluded for specific Symfony documentation files are not relevant to project and were thus removed:
     ```
     exclude_rule_for_file:
         - path: configuration/multiple_kernels.rst
           rule_name: replacement
         - path: page_creation.rst
           rule_name: no_php_open_tag_in_code_block_php_directive
         - path: frontend/create_ux_bundle.rst
           rule_name: argument_variable_must_match_type
     ```

3. **Cleaned Up Whitelist:**
   - The whitelist included many lines specific to Symfony’s documentation structure and terminology which do not apply to Foundry. These were removed to avoid unnecessary whitelist entries that do not match our documentation:
     ```
     whitelist:
         regex:
             - '/``.yml``/'
             - '/(.*)\.orm\.yml/' # currently DoctrineBundle only supports .yml
         lines:
             - 'in config files, so the old ``app/config/config_dev.yml`` goes to'
             - '#. The most important config file is ``app/config/services.yml``, which now is'
             - 'The bin/console Command'
             - '.. _`LDAP injection`: http://projects.webappsec.org/w/page/13246947/LDAP%20Injection'
             - '.. versionadded:: 2.7.2' # Doctrine
             - '.. versionadded:: 2.8.0' # Doctrine
             - '.. versionadded:: 1.9.0' # Encore
             - '.. versionadded:: 1.18' # Flex in setup/upgrade_minor.rst
             - '.. versionadded:: 1.0.0' # Encore
             - '.. versionadded:: 2.7.1' # Doctrine
             - '123,' # assertion for var_dumper - components/var_dumper.rst
             - '"foo",' # assertion for var_dumper - components/var_dumper.rst
             - '$var .= "Because of this `\xE9` octet (\\xE9),\n";'
             - '.. versionadded:: 0.2' # MercureBundle
             - '.. versionadded:: 3.6' # MonologBundle
             - '.. versionadded:: 3.8' # MonologBundle
             - '.. versionadded:: 3.5' # Monolog
             - '.. _`a feature to test applications using Mercure`: https://github.com/symfony/panther#creating-isolated-browsers-to-test-apps-using-mercure-or-websocket'
             - 'End to End Tests (E2E)'
     ```

Thank you!

**Review by nikophil — APPROVED** [review]

**Comment by nikophil** [comment]
Hi @cezarpopa 

thanks for this, this is a very nice addition!

**Comment by cezarpopa** [comment]
> Hi @cezarpopa 
> 
> thanks for this, this is a very nice addition!
> 
> 

Thank you, it's been my pleasure. I'll look around to see if I can help with anything else.

**Pull request merged**
